import {
  MigrationInterface,
  QueryRunner,
  Table,
  TableColumn,
  TableForeignKey,
  TableUnique,
} from 'typeorm';

/**
 * Initial schema. Written with the driver-agnostic Table API so it runs on both
 * SQLite (local/dev) and PostgreSQL (production). Primary key `uuid` values are
 * generated by the database (TypeORM `PrimaryGeneratedColumn('uuid')`), and
 * `createdAt`/`updatedAt` are managed columns populated by TypeORM.
 *
 * Tables are created parent-before-child so foreign keys resolve at creation
 * time (PostgreSQL validates FK references immediately; SQLite does not).
 */
export class InitSchema1787228547499 implements MigrationInterface {
  name = 'InitSchema1787228547499';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // PostgreSQL requires the uuid-ossp extension for `uuid_generate_v4()`,
    // which TypeORM uses as the default for PrimaryGeneratedColumn('uuid').
    if (queryRunner.connection.options.type === 'postgres') {
      await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
    }

    await queryRunner.createTable(
      new Table({
        name: 'UserContactTB',
        columns: [
          new TableColumn({ name: 'id', type: 'uuid', isPrimary: true, isGenerated: true, generationStrategy: 'uuid' }),
          new TableColumn({ name: 'email', type: 'varchar', length: '255', isNullable: false }),
          new TableColumn({ name: 'phoneNumber', type: 'varchar', length: '30', isNullable: false }),
          new TableColumn({ name: 'fax', type: 'varchar', length: '30', isNullable: true }),
          new TableColumn({ name: 'linkedInUrl', type: 'varchar', length: '512', isNullable: true }),
        ],
        uniques: [new TableUnique({ name: 'UQ_contact_email', columnNames: ['email'] })],
      }),
      true,
    );

    await queryRunner.createTable(
      new Table({
        name: 'UserAddressTB',
        columns: [
          new TableColumn({ name: 'id', type: 'uuid', isPrimary: true, isGenerated: true, generationStrategy: 'uuid' }),
          new TableColumn({ name: 'address', type: 'varchar', length: '255', isNullable: false }),
          new TableColumn({ name: 'city', type: 'varchar', length: '100', isNullable: false }),
          new TableColumn({ name: 'state', type: 'varchar', length: '100', isNullable: false }),
          new TableColumn({ name: 'country', type: 'varchar', length: '100', isNullable: false }),
          new TableColumn({ name: 'zipCode', type: 'varchar', length: '20', isNullable: false }),
        ],
      }),
      true,
    );

    await queryRunner.createTable(
      new Table({
        name: 'UserInfoTB',
        columns: [
          new TableColumn({ name: 'id', type: 'uuid', isPrimary: true, isGenerated: true, generationStrategy: 'uuid' }),
          new TableColumn({ name: 'profilePhoto', type: 'varchar', length: '512', isNullable: true }),
          new TableColumn({ name: 'firstName', type: 'varchar', length: '100', isNullable: false }),
          new TableColumn({ name: 'lastName', type: 'varchar', length: '100', isNullable: false }),
          new TableColumn({ name: 'dob', type: 'date', isNullable: false }),
          new TableColumn({ name: 'occupation', type: 'varchar', length: '100', isNullable: true }),
          new TableColumn({ name: 'gender', type: 'varchar', length: '20', isNullable: false }),
          new TableColumn({ name: 'createdAt', type: 'timestamp', isNullable: false }),
          new TableColumn({ name: 'updatedAt', type: 'timestamp', isNullable: false }),
          new TableColumn({ name: 'contactId', type: 'uuid', isNullable: true }),
          new TableColumn({ name: 'addressId', type: 'uuid', isNullable: true }),
        ],
        uniques: [
          new TableUnique({ name: 'UQ_userinfo_contact', columnNames: ['contactId'] }),
          new TableUnique({ name: 'UQ_userinfo_address', columnNames: ['addressId'] }),
        ],
        foreignKeys: [
          new TableForeignKey({
            name: 'FK_userinfo_contact',
            columnNames: ['contactId'],
            referencedTableName: 'UserContactTB',
            referencedColumnNames: ['id'],
          }),
          new TableForeignKey({
            name: 'FK_userinfo_address',
            columnNames: ['addressId'],
            referencedTableName: 'UserAddressTB',
            referencedColumnNames: ['id'],
          }),
        ],
      }),
      true,
    );

    await queryRunner.createTable(
      new Table({
        name: 'UserAcademicsTB',
        columns: [
          new TableColumn({ name: 'id', type: 'uuid', isPrimary: true, isGenerated: true, generationStrategy: 'uuid' }),
          new TableColumn({ name: 'schoolName', type: 'varchar', length: '255', isNullable: false }),
          new TableColumn({ name: 'degree', type: 'varchar', length: '150', isNullable: true }),
          new TableColumn({ name: 'fieldOfStudy', type: 'varchar', length: '150', isNullable: true }),
          new TableColumn({ name: 'startDate', type: 'date', isNullable: true }),
          new TableColumn({ name: 'endDate', type: 'date', isNullable: true }),
          new TableColumn({ name: 'description', type: 'text', isNullable: true }),
          new TableColumn({ name: 'userId', type: 'uuid', isNullable: true }),
        ],
        foreignKeys: [
          new TableForeignKey({
            columnNames: ['userId'],
            referencedTableName: 'UserInfoTB',
            referencedColumnNames: ['id'],
            onDelete: 'CASCADE',
          }),
        ],
      }),
      true,
    );

    await queryRunner.createTable(
      new Table({
        name: 'AdminUser',
        columns: [
          new TableColumn({ name: 'id', type: 'uuid', isPrimary: true, isGenerated: true, generationStrategy: 'uuid' }),
          new TableColumn({ name: 'email', type: 'varchar', length: '255', isNullable: false }),
          new TableColumn({ name: 'passwordHash', type: 'varchar', isNullable: false }),
          new TableColumn({ name: 'createdAt', type: 'timestamp', isNullable: false }),
        ],
        uniques: [new TableUnique({ name: 'UQ_admin_email', columnNames: ['email'] })],
      }),
      true,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable('UserAcademicsTB');
    await queryRunner.dropTable('UserInfoTB');
    await queryRunner.dropTable('UserAddressTB');
    await queryRunner.dropTable('UserContactTB');
    await queryRunner.dropTable('AdminUser');
  }
}
